#!/usr/bin/env bash

cd "$(dirname "$0")" || exit

# If the .env file exists. use it to populate BIN_PATH_ROBO_PHP.
if [ ! -f vendor/bin/robo ]; then
  echo 'You must install composer dependencies before robo can be run.'
  exit 1
fi

# If the .env file exists. use it to populate BIN_PATH_ROBO_PHP.
if [ -f .env ]; then
  . .env
fi

# If there is no path to php override, use lando.
if [ -z "${BIN_PATH_ROBO_PHP}" ]; then
  BIN_PATH_ROBO_PHP="php"
else
  set -x
fi

${BIN_PATH_ROBO_PHP} vendor/bin/robo "$@"
